version: 2
registries:
  npm:
    type: npm-registry
    url: https://registry.npmjs.org/

updates:
  - package-ecosystem: "npm"
    directory: /
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: scope
    assignees:
      - "jdietrichdev"
  
  - package-ecosystem: "github-actions"
    directory: /
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: scope
    assignees:
      - "jdietrichdev"