name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
assignees: [jdietrichdev]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: |
        What actually happened? Include full errors, uncaught exceptions, stack traces, and relevant logs.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        Provide code snippet or brief description of how to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: |
        Suggest a fix/reason for the bug.
    validations:
      required: false
  - type: textarea
    id: info
    attributes:
      label: Additional Information
      description: |
        Any additional context and information that may be relevant for troubleshooting bug.
    validations:
      required: false
  - type: input
    id: package-version
    attributes: 
      label: Package Version
      description: |
        What version of the package are you using?
    validations: 
      required: true
  - type: checkboxes
    id: help
    attributes:
      label: Assistance
      description: Are you able to help with fixing this issue?
      options:
        - label: I may be able to implement this fix
        - label: I will need help implementing the fix
